#ifndef HYPERVIBE_CREDENTIAL_BROKER_BRIDGING_HEADER_H
#define HYPERVIBE_CREDENTIAL_BROKER_BRIDGING_HEADER_H

#import "../CredentialKeychainBridge.h"

#endif /* HYPERVIBE_CREDENTIAL_BROKER_BRIDGING_HEADER_H */
